export const ToolbarPropertiesUr = {
    ownerToolBar_heading_msg1: 'اشتہار کے مالک (Ad)',
    ownerToolBar_heading_msg: 'شوسےٹی',
    step1_btn_label_msg: ' مرحلہ نمبر 1: اشتہار جمع کرائیں',
    step2_btn_label_msg: ' مرحلہ نمبر 2: علاقہ جمع کرائیں',
    myads_btn_label_msg: 'میرا سب اشتہار',  
  };

export const UploadAdScreenPropertiesUr = {
    upload_ads_step1_heading_msg: 'مرحلہ نمبر 1: یہاں اشتہار جمع کرائیں',
    use_phone_auth_msg: 'فون کے ساتھ',
    use_email_auth_msg: 'ای میل کے ساتھ',
    phone_input_label_msg: 'فون نمبر',
    email_input_label_msg: 'ای میل',
    secretNum_input_label_msg: 'تین ہندسہ خفیہ نمبر',
    ad_type_heading_msg: 'وقت ؟',
    ad_type_12_hrs_msg: 'بارہ گھنٹے کے لئے اشتہار',
    ad_type_1_week_msg: 'ایک ہفتہ کے لیے اشتہار',
    ad_type_1_month_msg: 'ایک ماہ کے لئے اشتہار',        
    ad_type_1_year_msg: 'ایک سال کے لئے اشتہار',
    chose_ad_label_msg: 'बराबर वाले स्थान पर दबाएँ और अपना एड (Ad) चुने',
    required_label_msg: 'اہم ہے *',
    desc_offer_label_msg: 'یہاں  آپ  اشتہار  وضاحت کریں ,ضرورت نہیں ہے',
    required_email_phone_label_msg: ' اہم ہے * "فون نمبر" اور "ای میل" صرف ایک',
    label_submit_upload_ads_msg: 'اسے بھیجیں',
    your_ads_label_msg: ':آپ اشتہار',
    desc_word_length_label_msg: ':کل لمبائی',
    displayType_heading_msg: 'سائز کا انتخاب کریں؟',
    
    displayType1_msg: 'چھوٹا اشتہار',
    displayType2_msg: 'بڑا اشتہار',
    displayType3_msg: 'بہت بڑا اشتہار',
    status_label_msg: 'فعال',
    status_yes_label_msg: 'شروع کریں',
    status_no_label_msg: 'رک جاؤ',    
    chose_category_label_msg: 'آپ کے کاروبار کی وضاحت کرنے والے زمرے کا انتخاب کریں',
    };
  
export const TargetAreaPropertiesUr = {    
    
    TargetArea_step2_heading_msg: ' مرحلہ نمبر 2: وہ جگہ جہاں اشتہار دکھانا ہے',
    use_phone_auth_msg: 'فون کے ساتھ',
    use_email_auth_msg: 'ای میل کے ساتھ',
    phone_input_label_msg: 'فون نمبر',
    email_input_label_msg: 'ای میل',
    secretNum_input_label_msg: 'تین ہندسہ خفیہ نمبر',
    load_ta_label_msg: 'یہاں لاؤ ہدف علاق',
    ta_heading_msg:  '_msg:ہدف علاق',
    sample_address_syntax_msg: 'بتاؤ بہت  علاق ہدف: شہر , شہر , حالت',
    sample_address_start_msg: ':نمونہ دیکھیں پتہنیچے',
    sample_address_1_msg: 'Noida, UP ',
    sample_address_2_msg: 'Sector 1, noida, up',
    sample_address_3_msg: '4th Road, Deepak estate, Sector 1, Telangana, Hyderabad',
    sample_address_4_msg: 'Gali #5, Ashok vihar, Delhi',
    address_label_part1_msg: 'ہدف علاق',
    address_label_part2_msg: ': (نمونہ دیکھیں پتہ اوپر) ',
    remove_label_msg:'اسے ہٹائیں',
    add_targetarea_label_msg: 'اضافہ ایک ہدف علاق',
    label_submit_targetarea_msg: 'اسے بھیجیں',
    ta_loading_plz_msg: 'انتظار کرو,آپ سب علاق یہاں دکھائے گا',
    ta_save_success_msg: 'آپ ہدف علاق ہم تک پہنچا ہے',
    required_email_phone_label_msg: ' اہم ہے * "فون نمبر" اور "ای میل" صرف ایک',
    required_label_msg: 'اہم ہے *',      
};

export const OwnerSideNavPropertiesUr = {  
    owner_login_msg: 'Owner Login',
    owner_past_data_msg: 'Owner past data',
    clients_msg: 'Clients',
    contact_msg: 'Contact',
};

export const ListMyAddPropertiesUr = { 
    list_myads_heading_msg: 'میرا سب اشتہار یہاں ہے, یہاں اشتہار میں تبدیل کر سکتے ہیں',
    use_phone_auth_msg: 'فون کے ساتھ',
    use_email_auth_msg: 'ای میل کے ساتھ',
    phone_input_label_msg: 'فون نمبر',
    email_input_label_msg:  'ای میل',
    secretNum_input_label_msg: 'تین ہندسہ خفیہ نمبر',
    load_my_ads_label_msg: 'یہاں لاؤ  میرا سب اشتہار',
    th_heading_col1_msg: '#',
    th_heading_col2_msg: 'एड का प्रकार & एड का नाम',
    th_heading_col3_msg: 'एड या ऑफर का वर्णन',
    th_heading_col4_msg: 'एड',
    th_heading_col5_msg: 'تبدیلی',
    ad_type_label_msg: 'اشتہار مدت: ',
    ad_image_label_msg: 'اشتہار تصویر:',
    created_on_label_msg: ':پر بنایا',
    status_on_label_msg: ':فعال',
    
    required_email_phone_label_msg: ' اہم ہے * "فون نمبر" اور "ای میل" صرف ایک',
    required_label_msg: 'اہم ہے *',
    active_date_label_msg: ':فعال تاریخ',
};

export const CommonMessagesUr = { 
    myAdsList_loading_plz_msg: 'انتظار کرو,آپ سب اشتہار یہاں دکھائے گا',
    msg_refresh_msg: ' دبائیں۔ انٹرنیٹ چیک کریں F5', 
    msg_ok_msg: 'اچھی',
    msg_bad_msg: 'غلط فرمائش',
    usr_not_found_msg: 'صارف نہیں ملا. برائے کرم فون / ای میل اور خفیہ نمبر دیکھیں',
    file_not_acc_msg: ' تصویر قبول نہیں کیا',
    chk_phn_eml_msg: 'صارف نہیں ملا. برائے کرم فون / ای میل اور خفیہ نمبر دیکھیں',
    store_fail_msg: 'مواد ذخیرہ کرنے سے قاصر۔ براہ کرم دوبارہ کوشش کریں۔ یا ہمیں کال کریں',            
    size_heavy_msg: 'فائل کا سائز اس سے کم ہونا چاہئے MB 1',
    limit_reach_msg: 'حد ہوگئی ،برائے مہربانی اپنے میں سے ایک میں ترمیم کریں اشتہار',
    trgt_stored_msg: 'Target Area stored.',
    modify_done_msg: 'اشتہار ترمیم ہو گئی',
    file_upld_done_msg: 'اشتہار پہنچا. تصدیق کریں Target Area.',
};
