export const ToolbarPropertiesPa = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'ਸ਼ੋਸੀਟੀ',
};

export const LoginScreenPropertiesPa = {
    use_phone_auth_msg: 'ਵਰਤੋਂ ਫੋਨ',
    use_email_auth_msg: 'ਵਰਤੋਂ ਈ - ਮੇਲ',
    phone_input_label_msg: 'ਫੋਨ ਗਿਣਤੀ',
    email_input_label_msg: 'ਈ - ਮੇਲ',
    secretNum_input_label_msg: '3-ਅੰਕ ਗੁਪਤ ਗਿਣਤੀ',
    required_label_msg: '* ਲੋੜੀਂਦਾ',
    required_email_phone_label_msg: '* ਲੋੜੀਂਦਾ (ਈ - ਮੇਲ / ਫੋਨ)',    
    label_submit_upload_ads_msg: 'ਇਸ ਨੂੰ ਭੇਜੋ',  
    login_heading_msg: 'ਦੱਸਣਾ ਦੱਸੋ',  
    login_app_desc_1_msg: 'ਆਪਣੀ ਕਿਸੇ ਵੀ ਜਗ੍ਹਾ ਦੀ ਸਾਰੀ ਦੁਕਾਨ ਜਾਂ ਕਾਰੋਬਾਰ ਵੇਖੋ',    
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'ਉਨ੍ਹਾਂ ਦੀਆਂ ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਕੀ ਨਵਾਂ ਹੈ ਅਤੇ ਵਪਾਰੀ ਦੇ ਨਾਲ ਛੋਟ',
    login_app_desc_3_msg: 'Shoppingਨਲਾਈਨ ਖਰੀਦਦਾਰੀ ਨਾਲੋਂ ਬਾਹਰ ਖਰੀਦਦਾਰੀ ਵਧੇਰੇ ਮਜ਼ੇਦਾਰ ਹੈ',
    r_u_new_user_label_msg:'ਨਵਾਂ ਯੂਜ਼ਰ >>',
    go_to_register_here_msg: 'ਰਜਿਸਟਰਡ',
    msg_refresh_msg: 'F5 ਦਬਾਓ. ਇੰਟਰਨੈਟ ਕਨੈਕਸ਼ਨ ਦੀ ਜਾਂਚ ਕਰੋ',
    usr_not_exist_msg: 'ਕਿਰਪਾ ਕਰਕੇ ਸਹੀ ਜਾਣਕਾਰੀ ਦਿਓ',    
    forgot_secret_number_msg: 'ਕੀ ਆਪਣਾ ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ ਹੋ?, ਇਥੇ ਦਬਾਓ',
    reset_secret_heading_msg: '  ਲਈ ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    reset_secret_message_msg: 'ਅਸੀਂ ਤੁਹਾਡੇ ਨਾਲ ਦਿੱਤੇ ਫੋਨ ਨੰਬਰ ਜਾਂ ਈਮੇਲ ਤੇ ਸੰਪਰਕ ਕਰਾਂਗੇ',
    reset_secret_messag2_msg: 'ਅਸੀਂ ਜਲਦੀ ਹੀ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਾਂਗੇ',
    go_to_login_here_msg: 'ਦੱਸਣਾ ਦੱਸੋ',
};

export const RegisterScreenPropertiesPa = {
    userName_input_label_msg: 'ਵਪਾਰ ਨਾਮ',
    secret_number_required_msg: '*ਗੁਪਤ ਗਿਣਤੀ ਲੋੜ ਹੈ',
    use_phone_auth_msg: 'ਵਰਤੋਂ ਫੋਨ',
    use_email_auth_msg: 'ਵਰਤੋਂ ਈ - ਮੇਲ',
    phone_input_label_msg: 'ਫੋਨ ਗਿਣਤੀ',
    email_input_label_msg: 'ਈ - ਮੇਲ',
    secretNum_input_label_msg: '3-ਅੰਕ ਗੁਪਤ ਗਿਣਤੀ',
    required_label_msg: '* ਲੋੜੀਂਦਾ',
    required_email_phone_label_msg: '* ਲੋੜੀਂਦਾ (ਈ - ਮੇਲ / ਫੋਨ)',
    label_submit_upload_ads_msg: 'ਇਸ ਨੂੰ ਭੇਜੋ',
    register_label_msg: 'ਰਜਿਸਟਰ',
    register_app_desc_1_msg: 'ਰਜਿਸਟਰ',
    register_app_desc_2_msg: '.....ਅਤੇ',
    register_app_desc_3_msg: 'ਆਪਣੀ ਕਿਸੇ ਵੀ ਜਗ੍ਹਾ ਦੀ ਸਾਰੀ ਦੁਕਾਨ ਜਾਂ ਕਾਰੋਬਾਰ ਵੇਖੋ',    
    register_app_desc_6_msg: 'ਕਾਗਜ਼ ਗਾਹਕਾਂ ਤੱਕ ਪਹੁੰਚਣ ਅਤੇ ਸੂਚਿਤ ਕਰਨ ਦਾ ਵਧੀਆ wayੰਗ ਹਨ',
    register_app_desc_7_msg: 'ਦੁਕਾਨ ਦੁਆਰਾ ਨੇੜੇ ਤੇ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ',
    register_app_desc_4_msg: 'ਉਨ੍ਹਾਂ ਦੀਆਂ ਪੇਸ਼ਕਸ਼ਾਂ ਅਤੇ ਕੀ ਨਵਾਂ ਹੈ ਅਤੇ ਵਪਾਰੀ ਦੇ ਨਾਲ ਛੋਟ',
    register_app_desc_5_msg: 'ਖਰੀਦਦਾਰੀ ਨਲਾਈਨ ਖਰੀਦਦਾਰੀ ਨਾਲੋਂ ਬਾਹਰ ਖਰੀਦਦਾਰੀ ਵਧੇਰੇ ਮਜ਼ੇਦਾਰ ਹੈ',
    
    already_a_user_label_msg:'ਤੁਸੀਂ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰ ਹੋ ਗਏ ਹੋ >>',
    go_to_login_here_msg: 'ਦੱਸਣਾ ਦੱਸੋ',
    usr_exist_msg: 'ਉਪਭੋਗਤਾ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ',
    msg_refresh_msg: 'F5 ਦਬਾਓ. ਇੰਟਰਨੈਟ ਕਨੈਕਸ਼ਨ ਦੀ ਜਾਂਚ ਕਰੋ',
    or_msg: 'ਜਾਂ',
  };
