export const ToolbarPropertiesBng = {
  ownerToolBar_heading_msg1: 'एड (Ad) এর মালিক ',
  ownerToolBar_heading_msg: 'শোসেটি',   
};

export const LoginScreenPropertiesBng = {
  use_phone_auth_msg: 'ফোন দিয়ে',
  use_email_auth_msg: 'ইমেল সহ',
  phone_input_label_msg: 'ফোন নম্বর',
  email_input_label_msg: 'ইমেল',
  secretNum_input_label_msg: '3 অঙ্ক গোপন নাম্বার',
  required_email_phone_label_msg: '* গুরুত্বপূর্ণ ("ফোন নম্বর" অথবা "ইমেল" অন্যতম)',
  required_label_msg: '* গুরুত্বপূর্ণ',
  label_submit_upload_ads_msg: 'এটা পাঠান',
  login_heading_msg: 'নিজেকে সনাক্ত করুন',  
  login_app_desc_1_msg: 'আপনার যে কোনও জায়গার সমস্ত দোকান বা ব্যবসা দেখুন',
  login_app_desc_2_msg: 'তাদের অফার এবং নতুন কি এবং বণিকের সাথে ছাড় রয়েছে',
  login_app_desc_3_msg: 'বাইরের শপিং অনলাইন শপিংয়ের চেয়ে বেশি মজাদার',
  login_app_desc_4_msg:'',
  login_app_desc_5_msg:'',
  r_u_new_user_label_msg:'নতুন ব্যবহারকারী >>',
  go_to_register_here_msg: 'রেজিষ্টারী বই',
  msg_refresh_msg: 'F5 টিপুন, ইন্টারনেট সংযোগ পরীক্ষা করুন',
  usr_not_exist_msg: 'দয়া করে সঠিক তথ্য দিন',
  forgot_secret_number_msg: 'আপনার পাসওয়ার্ড ভুলে গেছেন?, এখানে চাপ দিন',
  reset_secret_heading_msg: 'গোপন নাম্বার',
  reset_secret_message_msg: 'আমরা প্রদত্ত ফোন নম্বর বা ইমেল আপনার সাথে যোগাযোগ করব',
  reset_secret_messag2_msg: 'আমরা তোমার সাথে শীঘ্রই যোগাযোগ করবো',
  go_to_login_here_msg: 'নিজেকে সনাক্ত করুন',
  };

export const RegisterScreenPropertiesBng = {
    userName_input_label_msg: 'ব্যবসা নাম',
    secret_number_required_msg: '* গোপন নাম্বার গুরুত্বপূর্ণ',
    use_phone_auth_msg: 'ফোন দিয়ে',
    use_email_auth_msg: 'ইমেল সহ',
    phone_input_label_msg: 'ফোন নম্বর',
    email_input_label_msg: 'ইমেল',
    secretNum_input_label_msg: '3 অঙ্ক গোপন নাম্বার',
    required_label_msg: '* গুরুত্বপূর্ণ',
    required_email_phone_label_msg: '* গুরুত্বপূর্ণ ("ফোন নম্বর" অথবা "ইমেল" অন্যতম)',
    label_submit_upload_ads_msg: 'এটা পাঠান',
    register_label_msg: 'রেজিষ্টারী বই',
    register_app_desc_1_msg: 'রেজিষ্টারী বই',
    register_app_desc_2_msg: '.....এবং',
    register_app_desc_3_msg: 'আপনার যে কোনও জায়গার সমস্ত দোকান বা ব্যবসা দেখুন',
    register_app_desc_6_msg: 'কাগজপত্রগুলি গ্রাহকদের কাছে পৌঁছানোর এবং অবহিত করার দুর্দান্ত উপায়',
    register_app_desc_7_msg: 'দোকানে কাছাকাছি সময়ে তথ্য গ্রহণ করুন',
    register_app_desc_4_msg: 'তাদের অফার এবং নতুন কি এবং বণিকের সাথে ছাড় রয়েছে',
    register_app_desc_5_msg: 'বাইরের শপিং অনলাইন শপিংয়ের চেয়ে বেশি মজাদার',
        
    already_a_user_label_msg:'ইতিমধ্যে নিবন্ধভুক্ত >>',
    go_to_login_here_msg: 'নিজেকে সনাক্ত করুন',
    usr_exist_msg: 'ব্যবহারকারী ইতিমধ্যে রেজিষ্টারী',
    msg_refresh_msg: 'F5 টিপুন, ইন্টারনেট সংযোগ পরীক্ষা করুন',
    or_msg: 'বা',
  };
