export const ToolbarPropertiesTe = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'షోసేటీ',
};

export const LoginScreenPropertiesTe = {
    use_phone_auth_msg: 'వా డు ఫోన్',
    use_email_auth_msg: 'వా డు ఇమెయిల్',
    phone_input_label_msg: 'ఫోన్ సంఖ్య',
    email_input_label_msg: 'ఇమెయిల్',
    secretNum_input_label_msg: '3-అంకెల రహస్యం సంఖ్య',
    required_label_msg: '* అవసరం',
    required_email_phone_label_msg: '* అవసరం (ఇమెయిల్ / ఫోన్)',    
    label_submit_upload_ads_msg: 'పంపండి',  
    login_heading_msg: 'గుర్తించండి గుర్తించండి',  
    login_app_desc_1_msg: 'మీ ఏదైనా స్థలం యొక్క అన్ని దుకాణం లేదా వ్యాపారాన్ని చూడండి',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'వారి ఆఫర్‌లు మరియు క్రొత్తవి మరియు వ్యాపారితో తగ్గింపు',
    login_app_desc_3_msg: 'ఆన్‌లైన్ షాపింగ్ కంటే వెలుపల షాపింగ్ చాలా సరదాగా ఉంటుంది',
    r_u_new_user_label_msg:'క్రొత్త వినియోగదారు >>',
    go_to_register_here_msg: 'నమోదు చేయబడింది',
    msg_refresh_msg: 'F5 నొక్కండి. ఇంటర్నెట్ కనెక్షన్‌ను తనిఖీ చేయండి',
    usr_not_exist_msg: 'దయచేసి సరైన సమాచారం ఇవ్వండి',    
    forgot_secret_number_msg: 'మీ పాస్‌వర్డ్ మర్చిపోయారా?, ఇక్కడ నొక్కండి',
    reset_secret_heading_msg: ' కోసం మమ్మల్ని సంప్రదించండి',
    reset_secret_message_msg: 'ఇచ్చిన ఫోన్ నంబర్ లేదా ఇమెయిల్ వద్ద మేము మిమ్మల్ని సంప్రదిస్తాము',
    reset_secret_messag2_msg: 'మేము త్వరలో మిమ్మల్ని సంప్రదిస్తాము',
    go_to_login_here_msg: 'గుర్తించండి గుర్తించండి',
};

export const RegisterScreenPropertiesTe = {
    userName_input_label_msg: 'వ్యాపారం పేరు',
    secret_number_required_msg: '*రహస్యం సంఖ్య అవసరం',
    use_phone_auth_msg: 'వా డు ఫోన్',
    use_email_auth_msg: 'వా డు ఇమెయిల్',
    phone_input_label_msg: 'ఫోన్ సంఖ్య',
    email_input_label_msg: 'ఇమెయిల్',
    secretNum_input_label_msg: '3-అంకెల అవసరం సంఖ్య',
    required_label_msg: '* అవసరం',
    required_email_phone_label_msg: '* అవసరం (ఇమెయిల్ / ఫోన్)',
    label_submit_upload_ads_msg: 'పంపండి',
    register_label_msg: 'నమోదు చేయండి',
    register_app_desc_1_msg: 'నమోదు చేయండి',
    register_app_desc_2_msg: '.....మరియు',
    register_app_desc_3_msg: 'మీ ఏదైనా స్థలం యొక్క అన్ని దుకాణం లేదా వ్యాపారాన్ని చూడండి',
    register_app_desc_6_msg: 'పేపర్లు కస్టమర్లను చేరుకోవడానికి మరియు తెలియజేయడానికి గొప్ప మార్గం',
    register_app_desc_7_msg: 'దుకాణం ద్వారా సమీపంలో సమాచారాన్ని స్వీకరించండి',
    register_app_desc_4_msg: 'వారి ఆఫర్‌లు మరియు క్రొత్తవి మరియు వ్యాపారితో తగ్గింపు',
    register_app_desc_5_msg: 'ఆన్‌లైన్ షాపింగ్ కంటే వెలుపల షాపింగ్ చాలా సరదాగా ఉంటుంది',
    
    already_a_user_label_msg:'మీరు ఇప్పటికే నమోదు చేసుకోండి >>',
    go_to_login_here_msg: 'గుర్తించండి గుర్తించండి',
    usr_exist_msg: "వినియోగదారు ఇప్పటికే ఉన్నారు",
    msg_refresh_msg: 'F5 నొక్కండి. ఇంటర్నెట్ కనెక్షన్‌ను తనిఖీ చేయండి',
    or_msg: 'లేదా',
  };
