export const ToolbarPropertiesMl = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'ഷോസെറ്റി',
};

export const LoginScreenPropertiesMl = {
    use_phone_auth_msg: 'ഉപയോഗിക്കുക ഫോൺ',
    use_email_auth_msg: 'ഉപയോഗിക്കുക ഇമെയിൽ',
    phone_input_label_msg: 'ഫോൺ നമ്പർ',
    email_input_label_msg: 'ഇമെയിൽ',
    secretNum_input_label_msg: '3-അക്കം രഹസ്യം നമ്പർ',
    required_label_msg: '* ആവശ്യമാണ്',
    required_email_phone_label_msg: '* ആവശ്യമാണ് (ഇമെയിൽ / ഫോൺ)',    
    label_submit_upload_ads_msg: 'അതു അയയ്ക്കുക',  
    login_heading_msg: 'തിരിച്ചറിയുക തിരിച്ചറിയുക',  
    login_app_desc_1_msg: 'നിങ്ങളുടെ ഏതെങ്കിലും സ്ഥലത്തെ എല്ലാ ഷോപ്പും ബിസിനസും കാണുക',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'അവരുടെ ഓഫറുകളും പുതിയതും വ്യാപാരിയുമായി കിഴിവുള്ളതും',
    login_app_desc_3_msg: 'ഓൺലൈൻ ഷോപ്പിംഗിനേക്കാൾ രസകരമാണ് പുറത്ത് ഷോപ്പിംഗ്',
    r_u_new_user_label_msg:'പുതിയ ഉപയോക്താവ് >>',
    go_to_register_here_msg: 'രജിസ്റ്റർ ചെയ്തു',
    msg_refresh_msg: 'F5 അമർത്തുക. ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിക്കുക',
    usr_not_exist_msg: 'ശരിയായ വിവരങ്ങൾ നൽകുക',    
    forgot_secret_number_msg: 'നിങ്ങളുടെ പാസ്‌വേഡ് മറന്നോ?, ഇവിടെ അമർത്തുക',
    reset_secret_heading_msg: 'നമ്പർ മാറ്റിയിരിക്കുന്നു ഇതിനായി ഞങ്ങളെ ബന്ധപ്പെടുക',
    reset_secret_message_msg: 'തന്നിരിക്കുന്ന ഫോൺ നമ്പറിലോ ഇമെയിലിലോ ഞങ്ങൾ നിങ്ങളെ ബന്ധപ്പെടും',
    reset_secret_messag2_msg: 'ഞങ്ങൾ ഉടൻ നിങ്ങളെ ബന്ധപ്പെടും',
    go_to_login_here_msg: 'തിരിച്ചറിയുക തിരിച്ചറിയുക',
};

export const RegisterScreenPropertiesMl = {
    userName_input_label_msg: 'ബിസിനസ്സ് പേര്',
    secret_number_required_msg: '*രഹസ്യം നമ്പർ ആവശ്യമാണ്',
    use_phone_auth_msg: 'ഉപയോഗിക്കുക ഫോൺ',
    use_email_auth_msg: 'ഉപയോഗിക്കുക ഇമെയിൽ',
    phone_input_label_msg: 'ഫോൺ നമ്പർ',
    email_input_label_msg: 'ഇമെയിൽ',
    secretNum_input_label_msg: '3-അക്കം രഹസ്യം നമ്പർ',
    required_label_msg: '* ആവശ്യമാണ്',
    required_email_phone_label_msg: '* ആവശ്യമാണ് (ഇമെയിൽ / ഫോൺ)',
    label_submit_upload_ads_msg: 'അതു അയയ്ക്കുക',
    register_label_msg: 'രജിസ്റ്റർ ചെയ്യുക',
    register_app_desc_1_msg: 'രജിസ്റ്റർ ചെയ്യുക',
    register_app_desc_2_msg: '.....ഒപ്പം',
    register_app_desc_3_msg: 'നിങ്ങളുടെ ഏതെങ്കിലും സ്ഥലത്തെ എല്ലാ ഷോപ്പും ബിസിനസും കാണുക',
    register_app_desc_6_msg: 'ഉപഭോക്താക്കളിലേക്ക് എത്തിച്ചേരാനും അറിയിക്കാനുമുള്ള മികച്ച മാർഗമാണ് പേപ്പറുകൾ',
    register_app_desc_7_msg: 'ഷോപ്പിനടുത്തുള്ള വിവരങ്ങൾ സ്വീകരിക്കുക',
    register_app_desc_4_msg: 'അവരുടെ ഓഫറുകളും പുതിയതും വ്യാപാരിയുമായി കിഴിവുള്ളതും',
    register_app_desc_5_msg: 'ഓൺലൈൻ ഷോപ്പിംഗിനേക്കാൾ രസകരമാണ് പുറത്ത് ഷോപ്പിംഗ്',
    
    already_a_user_label_msg:'നിങ്ങൾ നേരത്തെ രജിസ്റ്റർ ചെയ്തു >>',
    go_to_login_here_msg: 'തിരിച്ചറിയുക തിരിച്ചറിയുക',
    usr_exist_msg: "ഉപയോക്താവ് ഇതിനകം നിലവിലുണ്ട്",
    msg_refresh_msg: 'F5 അമർത്തുക. ഇന്റർനെറ്റ് കണക്ഷൻ പരിശോധിക്കുക',
    or_msg: 'അഥവാ',
  };
