export const ToolbarPropertiesHn = {
  ownerToolBar_heading_msg1: 'विज्ञापन का मालिक ',
  ownerToolBar_heading_msg: 'शोसेटी',
};

export const LoginScreenPropertiesHn = {
    use_phone_auth_msg: 'फोन के साथ',
    use_email_auth_msg: 'ईमेल के साथ',
    phone_input_label_msg: 'फोन नम्बर',
    email_input_label_msg: 'ईमेल',
    secretNum_input_label_msg: '३-अंक का गुप्त नम्बर',
    required_label_msg: '* ज़रूरी है',
    required_email_phone_label_msg: '* ज़रूरी है ("फोन नम्बर" या "ईमेल" में से एक)',
    label_submit_upload_ads_msg: 'भेज दें',
    login_heading_msg: 'पहचान बतायें ',  
    login_app_desc_1_msg: 'अपनी किसी भी जगह की सभी दुकान या व्यवसाय देखें',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'उनके प्रस्ताव और व्यापारी के साथ नए और डिस्काउंट पर क्या है',
    login_app_desc_3_msg: 'ऑनलाइन शॉपिंग की तुलना में बाहर की खरीदारी ज्यादा मजेदार है',
    r_u_new_user_label_msg:'नया उपयोगकर्त्ता  >>',
    go_to_register_here_msg: 'रजिस्टर करें',
    msg_refresh_msg: 'F5 दबाएं। इंटरनेट कनेक्शन की जाँच करें',
    usr_not_exist_msg: 'कृप्या सही जानकारी दें',
    forgot_secret_number_msg: 'क्या आप पासवर्ड भूल गए?, यहां दबाएं',
    reset_secret_heading_msg: 'गुप्त नम्बर के लिए हमसे संपर्क करें',
    reset_secret_message_msg: 'हम आपको दिए गए फ़ोन नंबर या ईमेल पर संपर्क करेंगे',
    reset_secret_messag2_msg: 'हम आपसे शीघ्र ही संपर्क करेंगे',
    go_to_login_here_msg: 'पहचान बतायें ',
  };

export const RegisterScreenPropertiesHn = {
    userName_input_label_msg: 'व्यवसाय नाम',
    secret_number_required_msg: '* गुप्त नम्बर ज़रूरी है',
    use_phone_auth_msg: 'फोन के साथ',
    use_email_auth_msg: 'ईमेल के साथ',
    phone_input_label_msg: 'फोन नम्बर',
    email_input_label_msg: 'ईमेल',
    secretNum_input_label_msg: '३-अंक का गुप्त नम्बर',
    required_label_msg: '* ज़रूरी है',
    required_email_phone_label_msg: '* ज़रूरी है ("फोन नम्बर" या "ईमेल" में से एक)',
    label_submit_upload_ads_msg: 'भेज दें',
    register_label_msg: 'रजिस्टर करें',
    register_app_desc_1_msg: 'रजिस्टर करें',
    register_app_desc_2_msg: '.....और',
    register_app_desc_3_msg: 'अपनी किसी भी जगह की सभी दुकान या व्यवसाय देखें',
    register_app_desc_6_msg: 'कागजात ग्राहकों तक पहुंचने और ग्राहकों को सूचित करने का एक शानदार तरीका है',
    register_app_desc_7_msg: 'दुकान से पास की जानकारी प्राप्त करें',
    register_app_desc_4_msg: 'उनके प्रस्ताव और व्यापारी के पास डिस्काउंट पर क्या है',
    register_app_desc_5_msg: 'ऑनलाइन शॉपिंग की तुलना में बाहर की खरीदारी ज्यादा मजेदार है',
    
    already_a_user_label_msg:'पहले रजिस्टर किया है >>',
    go_to_login_here_msg: 'पहचान बतायें ',
    usr_exist_msg: "फोन/ईमेल पहले से ही रजिस्टर है",
    msg_refresh_msg: 'F5 दबाएं। इंटरनेट कनेक्शन की जाँच करें',
    or_msg: 'या',
  };
