export const ToolbarPropertiesGj = {
  ownerToolBar_heading_msg1: 'જાહેરાત નો માલિક',
  ownerToolBar_heading_msg: 'શોસાયટી',
};

export const LoginScreenPropertiesGj = {
  use_phone_auth_msg: 'ફોન સાથે',
  use_email_auth_msg: 'ઇમેઇલ સાથે',
  phone_input_label_msg: 'ફોન નંબર',
  email_input_label_msg: 'ઇમેઇલ',
  secretNum_input_label_msg: '३-અંક ના ગુપ્ત નંબર',
  required_label_msg: '* મહત્વનું છે',
  required_email_phone_label_msg: '* મહત્વનું છે ("ફોન નંબર" અથવા "ઇમેઇલ" માનૂ એક)',
  label_submit_upload_ads_msg: 'મોકલો',
  login_heading_msg: 'સ્વ ઓળખવા',  
  login_app_desc_1_msg: 'તમારી કોઈપણ જગ્યાની બધી દુકાન અથવા વ્યવસાય જુઓ',
  login_app_desc_4_msg: '',
  login_app_desc_5_msg: '',
  login_app_desc_2_msg: 'તેમની offersફર અને નવી અને વેપારી સાથેના ડિસ્કાઉન્ટ પર',
  login_app_desc_3_msg: 'Shopping નલાઇન શોપિંગ કરતા બહારની શોપિંગ વધારે મજા આવે છે',
  r_u_new_user_label_msg:'નવા વપરાશકર્તા >>',
  go_to_register_here_msg: 'રજિસ્ટર',
  msg_refresh_msg: 'F5 દબાવો. ઇન્ટરનેટ કનેક્શન તપાસો',
  usr_not_exist_msg: 'કૃપા કરી સાચી માહિતી આપો',
  forgot_secret_number_msg: 'તમારો પાસવર્ડ ભૂલી ગયા છો?, અહીં દબાવો',
  reset_secret_heading_msg: 'ગુપ્ત નંબર માટે અમારો સંપર્ક કરો',
  reset_secret_message_msg: 'આપેલ ફોન નંબર અથવા ઇમેઇલ પર અમે તમારો સંપર્ક કરીશું',
  reset_secret_messag2_msg: 'અમે જલ્દી જ તમારો સંપર્ક કરીશું',
  go_to_login_here_msg: 'સ્વ ઓળખવા',
  };

export const RegisterScreenPropertiesGj = {
    userName_input_label_msg: 'Business Name',
    secret_number_required_msg: '* ગુપ્ત નંબર મહત્વનું છે',
    use_phone_auth_msg: 'ફોન સાથે',
    use_email_auth_msg: 'ઇમેઇલ સાથે',
    phone_input_label_msg: 'ફોન નંબર',
    email_input_label_msg: 'ઇમેઇલ',
    secretNum_input_label_msg: '३-અંક ના ગુપ્ત નંબર',
    required_label_msg: '* મહત્વનું છે',
    required_email_phone_label_msg: '* મહત્વનું છે ("ફોન નંબર" અથવા "ઇમેઇલ" માનૂ એક)',
    label_submit_upload_ads_msg: 'મોકલો',
    register_label_msg: 'રજિસ્ટર',
    register_app_desc_1_msg: 'રજિસ્ટર',
    register_app_desc_2_msg: '.....અને',
    register_app_desc_3_msg: 'તમારી કોઈપણ જગ્યાની બધી દુકાન અથવા વ્યવસાય જુઓ',
    register_app_desc_6_msg: 'કાગળો એ ગ્રાહકો સુધી પહોંચવા અને જાણવાની શ્રેષ્ઠ રીત છે',
    register_app_desc_7_msg: 'દુકાન દ્વારા નજીકની માહિતી મેળવો',
    register_app_desc_4_msg: 'તેમની તક આપે છે ફર અને નવી અને વેપારી સાથેના ડિસ્કાઉન્ટ પર',
    register_app_desc_5_msg: 'ખરીદી નલાઇન શોપિંગ કરતા બહારની શોપિંગ વધારે મજા આવે છે',
    
    already_a_user_label_msg:'પહેલેથી નોંધાયેલ છે >>',
    go_to_login_here_msg: 'સ્વ ઓળખવા',
    usr_exist_msg: "વપરાશકર્તા પહેલાથી જ અસ્તિત્વમાં છે",
    msg_refresh_msg: 'F5 દબાવો. ઇન્ટરનેટ કનેક્શન તપાસો',
    or_msg: 'અથવા',
  };
