export const ToolbarPropertiesTa = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'ஷோசெடி',
};

export const LoginScreenPropertiesTa = {
    use_phone_auth_msg: 'பயன்படுத்தவும் தொலைபேசி',
    use_email_auth_msg: 'பயன்படுத்தவும் மின்னஞ்சல்',
    phone_input_label_msg: 'தொலைபேசி எண்',
    email_input_label_msg: 'மின்னஞ்சல்',
    secretNum_input_label_msg: '3-இலக்க ரகசியம் எண்',
    required_label_msg: '* தேவை',
    required_email_phone_label_msg: '* தேவை (மின்னஞ்சல் / தொலைபேசி)',    
    label_submit_upload_ads_msg: 'அதை அனுப்ப',  
    login_heading_msg: 'அடையாளம் அடையாளம்',  
    login_app_desc_1_msg: 'உங்கள் எந்த இடத்தின் அனைத்து கடை அல்லது வணிகத்தையும் காண்க',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'அவர்களின் சலுகைகள் மற்றும் புதியவை மற்றும் வணிகரிடம் தள்ளுபடி',
    login_app_desc_3_msg: 'ஆன்லைன் ஷாப்பிங்கை விட வெளியே ஷாப்பிங் செய்வது மிகவும் வேடிக்கையாக உள்ளது',
    r_u_new_user_label_msg:'புதிய பயனர் >>',
    go_to_register_here_msg: 'பதிவு செய்யப்பட்டுள்ளது',
    msg_refresh_msg: 'F5 ஐ அழுத்தவும். இணைய இணைப்பைச் சரிபார்க்கவும்',
    usr_not_exist_msg: 'சரியான தகவலைக் கொடுங்கள்',    
    forgot_secret_number_msg: 'உங்கள் கடவுச்சொல்லை மறந்துவிட்டீர்களா?, இங்கே அழுத்தவும்',
    reset_secret_heading_msg: ' எங்களை தொடர்பு கொள்ளவும்',
    reset_secret_message_msg: 'கொடுக்கப்பட்ட தொலைபேசி எண் அல்லது மின்னஞ்சலில் நாங்கள் உங்களைத் தொடர்புகொள்வோம்',
    reset_secret_messag2_msg: 'விரைவில் உங்களைத் தொடர்புகொள்வோம்',
    go_to_login_here_msg: 'அடையாளம் அடையாளம்',
};

export const RegisterScreenPropertiesTa = {
    userName_input_label_msg: 'வணிகத்தின் பெயர்',
    secret_number_required_msg: '*ரகசியம் எண் தேவை',
    use_phone_auth_msg: 'பயன்படுத்தவும் தொலைபேசி',
    use_email_auth_msg: 'பயன்படுத்தவும் மின்னஞ்சல்',
    phone_input_label_msg: 'தொலைபேசி எண்',
    email_input_label_msg: 'மின்னஞ்சல்',
    secretNum_input_label_msg: '3-இலக்க ரகசியம் எண்',
    required_label_msg: '* தேவை',
    required_email_phone_label_msg: '* தேவை (மின்னஞ்சல் / தொலைபேசி)',
    label_submit_upload_ads_msg: 'அதை அனுப்ப',
    register_label_msg: 'பதிவு',
    register_app_desc_1_msg: 'பதிவு',
    register_app_desc_2_msg: '.....மற்றும்',
    register_app_desc_3_msg: 'உங்கள் எந்த இடத்தின் அனைத்து கடை அல்லது வணிகத்தையும் காண்க',
    register_app_desc_6_msg: 'வாடிக்கையாளர்களை அணுகவும் தெரிவிக்கவும் ஆவணங்கள் சிறந்த வழியாகும்',
    register_app_desc_7_msg: 'கடைக்கு அருகிலுள்ள தகவலைப் பெறுக',
    register_app_desc_4_msg: 'அவர்களின் சலுகைகள் மற்றும் புதியவை மற்றும் வணிகரிடம் தள்ளுபடி',
    register_app_desc_5_msg: 'ஆன்லைன் ஷாப்பிங்கை விட வெளியே ஷாப்பிங் செய்வது மிகவும் வேடிக்கையாக உள்ளது',
    
    already_a_user_label_msg:'நீங்கள் ஏற்கனவே பதிவு செய்க >>',
    go_to_login_here_msg: 'அடையாளம் அடையாளம்',
    usr_exist_msg: "பயனர் ஏற்கனவே உள்ளார்",
    msg_refresh_msg: 'F5 ஐ அழுத்தவும். இணைய இணைப்பைச் சரிபார்க்கவும்',
    or_msg: 'அல்லது',
  };
