export const ToolbarPropertiesMr = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'शोसायटी',
};

export const LoginScreenPropertiesMr = {
    use_phone_auth_msg: 'वापरा फोन',
    use_email_auth_msg: 'वापरा ईमेल',
    phone_input_label_msg: 'फोन संख्या',
    email_input_label_msg: 'ईमेल',
    secretNum_input_label_msg: '3-अंक गुप्त संख्या',
    required_label_msg: '* आवश्यक',
    required_email_phone_label_msg: '* आवश्यक (ईमेल / फोन)',    
    label_submit_upload_ads_msg: 'पाठवा',  
    login_heading_msg: 'सांगा ओळखणे',  
    login_app_desc_1_msg: 'आपल्या कोणत्याही ठिकाणातील सर्व दुकान किंवा व्यवसाय पहा',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    login_app_desc_2_msg: 'त्यांच्या ऑफर आणि काय नवीन आहे आणि व्यापार्‍यावर सवलत आहे',
    login_app_desc_3_msg: 'बाहेरील शॉपिंगमध्ये ऑनलाइन शॉपिंगपेक्षा मजा येते',
    r_u_new_user_label_msg:'नवीन वापरकर्ता >>',
    go_to_register_here_msg: 'नोंदणीकृत',
    msg_refresh_msg: 'F5 दाबा. इंटरनेट कनेक्शन तपासा',
    usr_not_exist_msg: 'कृपया योग्य माहिती द्या',    
    forgot_secret_number_msg: 'आपला संकेतशब्द विसरलात?, येथे दाबा',
    reset_secret_heading_msg: ' गुप्त क्रमांक साठी आमच्याशी संपर्क साधा',
    reset_secret_message_msg: 'आम्ही दिलेल्या फोन नंबर किंवा ईमेल वर आपल्याशी संपर्क साधू',
    reset_secret_messag2_msg: 'आम्ही लवकरच आपल्याशी संपर्क साधू',
    go_to_login_here_msg: 'सांगा ओळखणे',
};

export const RegisterScreenPropertiesMr = {
    userName_input_label_msg: 'व्यवसायाचे नाव',
    secret_number_required_msg: '*गुप्त संख्या आवश्यक आहे',
    use_phone_auth_msg: 'वापरा फोन',
    use_email_auth_msg: 'वापरा ईमेल',
    phone_input_label_msg: 'फोन संख्या',
    email_input_label_msg: 'ईमेल',
    secretNum_input_label_msg: '3-अंक गुप्त संख्या',
    required_label_msg: '* आवश्यक',
    required_email_phone_label_msg: '* आवश्यक (ईमेल / फोन)',
    label_submit_upload_ads_msg: 'पाठवा',
    register_label_msg: 'नोंदणी करा',
    register_app_desc_1_msg: 'नोंदणी करा',
    register_app_desc_2_msg: '.....आणि',
    register_app_desc_3_msg: 'आपल्या कोणत्याही ठिकाणातील सर्व दुकान किंवा व्यवसाय पहा',
    register_app_desc_6_msg: 'पेपर हा ग्राहकांपर्यंत पोहोचण्याचा आणि माहिती देण्याचा उत्तम मार्ग आहे',
    register_app_desc_7_msg: 'दुकानातून जवळच माहिती मिळवा',
    register_app_desc_4_msg: 'त्यांच्या ऑफर आणि काय नवीन आहे आणि व्यापार्‍यावर सवलत आहे',
    register_app_desc_5_msg: 'बाहेरील शॉपिंगमध्ये ऑनलाइन शॉपिंगपेक्षा मजा येते',
    
    already_a_user_label_msg:'आपण आधी नोंदणी केली >>',
    go_to_login_here_msg: 'सांगा ओळखणे',
    usr_exist_msg: "वापरकर्ता आधीच अस्तित्वात आहे",
    msg_refresh_msg: 'F5 दाबा. इंटरनेट कनेक्शन तपासा',
    or_msg: 'किंवा',
  };
