export const ToolbarPropertiesEn = {
    ownerToolBar_heading_msg1: 'Owner Screen',
    ownerToolBar_heading_msg: 'Yes Local Market',
};

export const LoginScreenPropertiesEn = {
    use_phone_auth_msg: 'Use Phone',
    use_email_auth_msg: 'Use Email',
    phone_input_label_msg: 'Phone Number',
    email_input_label_msg: 'E-mail',
    secretNum_input_label_msg: '3-digit secret number',
    required_label_msg: '* required',
    required_email_phone_label_msg: '* required (Email / Phone)',    
    label_submit_upload_ads_msg: 'Submit',  
    login_heading_msg: 'Login',  
    login_app_desc_1_msg: 'See all shop or business of your any place',
    login_app_desc_2_msg: 'Their offers and what\'s new or what is on discount with the merchant',
    login_app_desc_3_msg: 'Outside shopping is more fun than online shopping.',
    login_app_desc_4_msg: '',
    login_app_desc_5_msg: '',
    r_u_new_user_label_msg:'New User >>',
    go_to_register_here_msg: 'Register',
    msg_refresh_msg: 'Press F5. Check Internet Connection',
    usr_not_exist_msg: 'Please give correct information',    
    forgot_secret_number_msg: 'Forgot secret number! Click here.',
    reset_secret_heading_msg: 'Contact for Secret Number',
    reset_secret_message_msg: 'We will contact you at given Phone number or Email',
    reset_secret_messag2_msg: 'We will contact you soon',
    go_to_login_here_msg: 'Login',
};

export const RegisterScreenPropertiesEn = {
    userName_input_label_msg: 'Business Name',
    secret_number_required_msg: '*Secret number is required',
    use_phone_auth_msg: 'Use Phone',
    use_email_auth_msg: 'Use Email',
    phone_input_label_msg: 'Phone Number',
    email_input_label_msg: 'E-mail',
    secretNum_input_label_msg: '3-digit secret number',
    required_label_msg: '* required',
    required_email_phone_label_msg: '* required (Email / Phone)',
    label_submit_upload_ads_msg: 'Submit',
    register_label_msg: 'Register',
    register_app_desc_1_msg: 'Register',
    register_app_desc_2_msg: '.....and',
    register_app_desc_3_msg: 'See all shop or business of your target area',
    register_app_desc_4_msg: 'Their offers and what\'s new or what is on discount with the merchant',
    register_app_desc_5_msg: 'Outside shopping is more fun than online shopping.',
    register_app_desc_6_msg: '',
    register_app_desc_7_msg: '',
    
    already_a_user_label_msg:'Already Registered >>',
    go_to_login_here_msg: 'Login',
    usr_exist_msg: "User already exist",
    msg_refresh_msg: 'Press F5. Check Internet Connection',
    or_msg: 'or',
  };
