/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bananabkend.bananaBkEnd1A.SecureClient.ngCartViewerSecureClient;

import java.util.LinkedHashMap;

/**
 *
 * @author sunjiv6
 */
public class CartViewerContentMapKeys {

    public CartViewerContentMapKeys() {
    }
    
   public LinkedHashMap<String,String> classComponentNames() {
        LinkedHashMap<String,String> map = new LinkedHashMap<String,String>();    
        map.put("ApiKeyDto_cl",""); 
        map.put("LoginScreen_cl",""); 
        map.put("MyAdsDto_cl",""); 
        map.put("RegisterScreen_cl",""); 
        map.put("ResponseSuccess_cl",""); 
        map.put("SearchLocation_cl",""); 
        map.put("UserDto_cl",""); 
        map.put("AuthServicesService_cl",""); 
        map.put("PropertiesComponent_cl",""); 
        map.put("MessageList_cl",""); 
        map.put("ToolbarMsg_cl",""); 
        map.put("ToolbarPlainComponent_cl",""); 
        map.put("ToolbarComponent_cl",""); 
        map.put("ViewerScreenMsg_cl",""); 
        map.put("ViewerScreenComponent_cl",""); 
        map.put("ViewerSideNavMsg_cl",""); 
        map.put("ViewerSidenavComponent_cl","");  
        map.put("ResetSecretNumComponent_cl","");  
        map.put("CallViewerComponent_cl","");  
        map.put("CartOrderCompletedMsg_cl","");  
        map.put("MyOrdersComponent_cl","");  
        map.put("CartToolbarMsg_cl","");  
        map.put("CartScreenComponent_cl",""); 
        map.put("CartViewerMsg_cl","");
        map.put("CartDeliveryAddressMsg_cl","");
        map.put("CartDeliveryAddressComponent_cl","");
        map.put("NewAddressForm_cl","");
        map.put("PayThruQRCodeMsg_cl","");
        map.put("MyOrdersMsg_cl","");
        map.put("CartToolbarComponent_cl","");
        map.put("OrderCompletedComponent_cl","");
        map.put("SharedService_cl","");
        return map;
    }
    
    public LinkedHashMap<String,String> messageAppProperties()
    {
        LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 
        map.put("ownerToolBar_heading_msg",""); 
        map.put("label_submit_upload_ads_msg",""); 
        map.put("search_placeholder_text_msg",""); 
        map.put("no_result_found_msg",""); 
        map.put("no_more_results_msg",""); 
        map.put("menu_instant_ads_msg",""); 
        map.put("menu_weekly_ads_msg",""); 
        map.put("menu_monthly_ads_msg",""); 
        map.put("menu_yearly_ads_msg",""); 
        map.put("reset_secret_number_msg",""); 
        map.put("login_msg",""); 
        map.put("logout_msg",""); 
        map.put("contactUs_msg",""); 
        map.put("filter_msg",""); 
        map.put("merchant_upload_screen_msg",""); 
        map.put("use_phone_auth_msg",""); 
        map.put("use_email_auth_msg",""); 
        map.put("phone_input_label_msg",""); 
        map.put("email_input_label_msg",""); 
        map.put("secretNum_input_label_msg",""); 
        map.put("required_label_msg",""); 
        map.put("required_email_phone_label_msg",""); 
        map.put("label_submit_upload_ads_msg",""); 
        map.put("usr_not_exist_msg",""); 
        map.put("forgot_secret_number_msg",""); 
        map.put("reset_secret_done_msg",""); 
        map.put("label_close_msg",""); 
        map.put("userName_input_label_msg",""); 
        map.put("secret_number_required_msg",""); 
        map.put("use_phone_auth_msg",""); 
        map.put("use_email_auth_msg",""); 
        map.put("phone_input_label_msg",""); 
        map.put("email_input_label_msg",""); 
        map.put("old_secretNum_input_label_msg",""); 
        map.put("required_label_msg",""); 
        map.put("required_email_phone_label","");
        map.put("label_submit_upload_ads","");
        map.put("login_heading","");
        map.put("login_app_desc_1","");
        map.put("login_app_desc_2_msg","");       
        map.put("login_app_desc_3_msg","");        
        map.put("login_app_desc_4_msg","");        
        map.put("login_app_desc_5","");
        map.put("r_u_new_user_label","");
        map.put("go_to_register_here_msg","");        
        map.put("reset_secret_heading_msg","");        
        map.put("search_placeholder_text_msg","");         
        map.put("label_submit_upload_ads_msg",""); 
        map.put("msg_refresh_msg",""); 
        map.put("login_msg","");
        map.put("logout_msg","");
        map.put("main_menu_msg","");        
        map.put("merchant_upload_screen_msg","");        
        map.put("merchant_sell_product_msg","");  
        map.put("my_orders_msg","");  
        map.put("status_msg","");  
        map.put("qnty_msg","");  
        map.put("my_orders_heading_msg","");  
        map.put("reset-secret-num-msg",""); 
        map.put("contact_us_heading_msg","");
        map.put("contact_email_sms_whatsapp_msg","");
        map.put("create_free_add_msg","");
        map.put("free_ads_heading_msg","");   
        map.put("user_menu_heading_msg",""); 
        map.put("status_msg",""); 
        map.put("my_orders_msg",""); 
        map.put("twoStepsToPay_msg",""); 
        map.put("thank_instruction_1_msg",""); 
        map.put("thank_instruction_2_msg",""); 
        map.put("thank_instruction_3_msg","");
        map.put("my_orders_heading_msg",""); 
        map.put("qnty_msg",""); 
        map.put("thank_heading_msg",""); 
        map.put("submit_msg",""); 
        map.put("delivery_address_heading_msg",""); 
        map.put("deliver_to_new_address_btn_msg",""); 
        map.put("new_address_msg",""); 
        map.put("transactionId_input_label_msg",""); 
        map.put("registered_email_phone_wrong_msg",""); 
        map.put("deliver_to_address_btn_msg",""); 
        map.put("transaction_number_exist_msg",""); 
        map.put("failed_msg","");
        map.put("address_heading_msg","");
        map.put("confirm_address_heading_msg","");
        map.put("confirm_address_btn_msg","");
        map.put("login_required_msg",""); 
        map.put("placeOrder_msg",""); 
        map.put("orderPlaced_msg",""); 
        map.put("orderConfirm_msg",""); 
        map.put("orderRemove_msg",""); 
        map.put("dontDelete_msg",""); 
        map.put("confirmRemove_msg",""); 
        map.put("ru_sureDelete_msg",""); 
        map.put("currency_msg",""); 
        map.put("cart_heading_msg",""); 
        map.put("cart_empty_msg","");
        map.put("qntty_msg","");
        map.put("pay_msg","");
        map.put("cart_cost_tax_msg","");
        map.put("total_cost_msg",""); 
        map.put("confirm_order_msg",""); 
        map.put("refresh_cost_msg",""); 
        map.put("imp_instructions_msg",""); 
        map.put("instructions_1_msg",""); 
        map.put("instructions_2_msg",""); 
        map.put("instructions_3_msg","");
        
       return map;
    }

   public LinkedHashMap<String,String>  constantsInPropertios(){
        LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 
        map.put("CartToolbarPropertiesBng","");
        map.put("CartToolbarPropertiesEn","");
        map.put("CartToolbarPropertiesGj","");
        map.put("CartToolbarPropertiesHn","");
        map.put("CartToolbarPropertiesKn","");
        map.put("CartToolbarPropertiesMl","");
        map.put("CartToolbarPropertiesMr","");
        map.put("CartToolbarPropertiesPa","");
        map.put("CartToolbarPropertiesTa","");
        map.put("CartToolbarPropertiesTe","");
        map.put("CartToolbarPropertiesUr","");
        
        map.put("CartViewerScreenPropertiesBng","");
	map.put("CartViewerScreenPropertiesEn","");
	map.put("CartViewerScreenPropertiesGj","");
	map.put("CartViewerScreenPropertiesHn","");
	map.put("CartViewerScreenPropertiesKn","");
	map.put("CartViewerScreenPropertiesMl","");
	map.put("CartViewerScreenPropertiesMr","");
	map.put("CartViewerScreenPropertiesPa","");
	map.put("CartViewerScreenPropertiesTa","");
	map.put("CartViewerScreenPropertiesTe","");
	map.put("CartViewerScreenPropertiesUr","");        
        
        map.put("CartDeliveryAddressPropertiesBng","");
	map.put("CartDeliveryAddressPropertiesEn","");
	map.put("CartDeliveryAddressPropertiesGj","");
	map.put("CartDeliveryAddressPropertiesHn","");
	map.put("CartDeliveryAddressPropertiesKn","");
	map.put("CartDeliveryAddressPropertiesMl","");
	map.put("CartDeliveryAddressPropertiesMr","");
	map.put("CartDeliveryAddressPropertiesPa","");
	map.put("CartDeliveryAddressPropertiesTa","");
	map.put("CartDeliveryAddressPropertiesTe","");
	map.put("CartDeliveryAddressPropertiesUr","");
        
        map.put("CartOrderCompletedPropertiesBng","");
        map.put("CartOrderCompletedPropertiesEn","");
        map.put("CartOrderCompletedPropertiesGj","");
        map.put("CartOrderCompletedPropertiesHn","");
        map.put("CartOrderCompletedPropertiesKn","");
        map.put("CartOrderCompletedPropertiesMl","");
        map.put("CartOrderCompletedPropertiesMr","");
        map.put("CartOrderCompletedPropertiesPa","");
        map.put("CartOrderCompletedPropertiesTa","");
        map.put("CartOrderCompletedPropertiesTe","");
        map.put("CartOrderCompletedPropertiesUr","");
        
        map.put("MyOrdersPropertiesBng","");
        map.put("MyOrdersPropertiesEn","");
        map.put("MyOrdersPropertiesGj","");
        map.put("MyOrdersPropertiesHn","");
        map.put("MyOrdersPropertiesKn","");
        map.put("MyOrdersPropertiesMl","");
        map.put("MyOrdersPropertiesMr","");
        map.put("MyOrdersPropertiesPa","");
        map.put("MyOrdersPropertiesTa","");
        map.put("MyOrdersPropertiesTe","");
        map.put("MyOrdersPropertiesUr","");
        return map;
    }
       
    public LinkedHashMap<String,String>  methods(){

            LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 

            map.put("getApiKey_mt","");
            map.put("searchAndLoadAdsForLoc_mt","");
            map.put("getRequestCreated_mt","");
            map.put("callGetAPIKey_mt","");
            map.put("getMsg_mt","");
            map.put("searchFormValidatorSuccess_mt","");
            map.put("placeholderText_mt","");
            map.put("onSubmit_mt","");
            map.put("showSideNav_mt","");
            map.put("hideSideNav_mt","");
            map.put("changeLang_mt","");
            map.put("callLoadAdsForNewSearch_mt","");
            map.put("loadAds_mt","");
            map.put("createImageFromBlob_mt","");
            map.put("sendGetReq_mt","");
            map.put("onScroll_mt","");
            map.put("userInfo_mt","");
            map.put("loadCategory_mt","");
            map.put("logout_mt","");
            map.put("changeLang_mt","");
            map.put("callLoadAdsForNewSearch_mt","");
            map.put("arrivalToThePage_mt","");
            map.put("corruptEveryThing_mt","");
            map.put("loadAds_mt","");
            map.put("favClicked_mt","");
            map.put("saveLikedItems_mt","");
            map.put("loadLikedItems_mt","");
            map.put("selectLikedAds_mt","");
            map.put("createImageFromBlob_mt","");
            map.put("onScroll_mt","");
            map.put("sendClickEvent_mt","");        
            map.put("getClickEvent_mt","");        
            map.put("sendLoadAdsClickEvent_mt","");        
            map.put("getLoadAdsClickEvent_mt","");        
            map.put("getSearch_mt","");
            map.put("readApiKeyDto_mt","");
            map.put("getAllCategory_mt","");
            map.put("getUserInfo_mt","");
            map.put("getImageRequestCreated_mt","");        
            map.put("saveLikedItemsId_mt","");        
            map.put("loadLikedItemsId_mt","");        
            map.put("resetSecretNum_mt","");
            map.put("setApiKeyDto_mt","");
            map.put("resetFormValidatorSuccess_mt","");
            map.put("onClose_mt","");         
            map.put("activatePhoneContent_mt","");        
            map.put("activateEmailContent_mt","");        
            map.put("sendLogInOutClickEvent_mt","");        
            map.put("getLogInOutClickEvent_mt","");        
            map.put("getLoginId_mt","");        
            map.put("getLoginName_mt","");      
            map.put("loadProperties_mt","");      
            map.put("addProdToCart_mt","");      
            map.put("sendChangeLangEvent_mt","");          
            map.put("getChangeLangEvent_mt","");      
            map.put("getLogout_mt","");              
            map.put("dontDelete_mt","");      
            map.put("setSelecetdFilter_mt","");              
            map.put("orderDelete_mt","");              
            map.put("orderDeleteConfirm_mt","");  
            map.put("sendLoadLikedAdsClickEvent_mt","");
            map.put("getLoadLikedAdsClickEvent_mt","");
            map.put("callLoadLikedAds_mt","");
            map.put("loadMyLikedAds_mt","");
            map.put("loadCartProd_mt","");
            map.put("transSubmit_mt","");
            map.put("listAllOrders_mt","");
            map.put("filterSelected_mt","");
            map.put("loadLikedAds_mt","");
            map.put("cartOrderConfirm_mt","");
            map.put("addToCart_mt",""); 
            map.put("addProdToCart_mt","");
            map.put("addressConfirm_mt","");
            map.put("newAddressConfirm_mt","");
            map.put("finalAddressConfirm_mt","");
            map.put("finalAddressConfirm1_mt",""); 
            map.put("getCartProds_mt",""); 
            map.put("getOrderedProds_mt",""); 
            map.put("getAllOrders_mt","");         
            map.put("getSelectedAdType_mt","");   
            map.put("getSelectedFilter_mt","");   
            map.put("setSelecetdAdType_mt","");
            return map;
    }
    
   public LinkedHashMap<String,String>  selectorTags(){
        
            LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 
            map.put("cart-order-completed-msg","");
            map.put("app-order-completed","");
            
            map.put("cart-order-completed-msg","");
            map.put("app-my-orders","");  
            map.put("cart-delivery-address-msg","");  
            map.put("app-cart-delivery-address","");  
            map.put("cart-viewer-msg","");  
            map.put("app-cart-screen","");  
            map.put("cart-toolbar-msg","");  
            map.put("app-cart-toolbar",""); 
//            map.put("app-user-settings",""); 
//            map.put("app-toolbar",""); 
//            map.put("contact-us-screen-msg",""); 
//            map.put("pay-thru-qr-code-msg",""); 
            return map;
    }
    
   public LinkedHashMap<String,String>  variables(){
        
        LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 

        map.put("updatedOn_vb","");
        map.put("apikey_vb","");
        map.put("search_vb","");
        map.put("ownerPhone_vb","");
        map.put("ownerEmail_vb","");
        map.put("secretNumber_vb","");
        map.put("identify_vb","");
        map.put("userName_vb","");
        map.put("message_vb","");
        map.put("status_vb","");
        map.put("searchForm_vb","");
        map.put("search_vb","");
        map.put("userId_vb","");
        map.put("baseUrl_vb","");
        map.put("apiKeyDto_vb","");
        map.put("loginApiKey_vb","");
        map.put("searchAndLoadAdsForLocUri_vb","");
        map.put("ownerGetOneImage_vb","");
        map.put("apiKeyDto1_vb","");
        map.put("formData_vb","");
        map.put("http_vb","");
        map.put("message_vb","");
        map.put("messageSeek_vb","");
        map.put("finalMessage_vb","");
        map.put("searchLocation_vb","");
        map.put("searchArr_vb","");
        map.put("searchIndex_vb","");
        map.put("viewerScreenComponent_vb","");
        map.put("authServicesService_vb","");
        map.put("apiKeyDto_vb","");
        map.put("userDto_vb","");
        map.put("searchForm_vb","");
        map.put("router_vb","");
        map.put("route_vb","");
        map.put("userId_vb","");
        map.put("placeholderText_vb","");
        map.put("myAdsDto_vb","");
        map.put("language_vb","");
        map.put("awaitingSearchMsg_vb","");
        map.put("searchDone_vb","");
        map.put("messageList_vb","");
        map.put("isValid","");
        map.put("searchIndex_vb","");
        map.put("searchDone_vb","");
        map.put("error_vb","");
        map.put("messageList_vb","");
        map.put("showSideNavToggle_vb","");
        map.put("lang_vb","");
        map.put("goto_vb","");
        map.put("imageIndex_vb","");
        map.put("imageIndexInc_vb","");
        map.put("currentSearch_vb","");
        map.put("userDto_vb","");
        map.put("authServicesService_vb","");
        map.put("searchLocation_vb","");
        map.put("apiKeyDto_vb","");
        map.put("searchForm_vb","");
        map.put("pageNum_vb","");
        map.put("language_vb","");
        map.put("subscription","");
        map.put("everySecond","");
        map.put("newSearch_vb","");
        map.put("scrollCalled_vb","");
        map.put("scrollAns_vb","");
        map.put("userDto_vb","");
        map.put("formData_vb","");
        map.put("reader_vb","");
        map.put("image_vb","");
        map.put("imageToShow_vb","");
        map.put("i_vb","");
        map.put("data_vb","");
        map.put("error_vb","");   
        map.put("clickEventSubscription_vb","");   
        map.put("timeSubscription_vb","");   
        map.put("everySecond_vb","");   
        map.put("userLogin_vb","");   
        map.put("categoryDto_vb","");   
        map.put("logout_vb","");   
        map.put("menu_instant_ads_vb","");           
        map.put("menu_weekly_ads_vb","");           
        map.put("menu_monthly_ads_vb","");   
        map.put("menu_yearly_ads_vb","");           
        map.put("reset_secret_number_vb","");           
        map.put("merchant_upload_screen_vb","");          
        map.put("contactUs_vb","");           
        map.put("filter_vb","");     
        map.put("viewerSideNavMsg_vb","");           
        map.put("comma_vb","");
        map.put("currentSearch_vb","");
        map.put("authServicesService_vb","");
        map.put("favClicked_vb","");
        map.put("viewerScreenMsg_vb","");
        map.put("likedItemIds_vb","");
        map.put("clickEventsubscription_vb","");
        map.put("subscription_vb","");
        map.put("everySecond_vb","");
        map.put("newSearch_vb","");
        map.put("scrollCalled_vb","");
        map.put("scrollAns_vb","");
        map.put("currentSearch_vb","");
        map.put("sharedService_vb","");
        map.put("pageName_vb","");
        map.put("toolbarMsg_vb","");
        map.put("isValid_vb","");
        map.put("old_secretNumberValidator_vb","");
        map.put("secretNumberValidator_vb","");
        map.put("authorizeDone_vb","");
        map.put("loginScreen_vb","");
        map.put("loginForm_vb","");
        map.put("togglePhoneActive_vb","");
        map.put("identifyPhoneValidator_vb","");
        map.put("identifyEmailValidator_vb","");
        map.put("arrivalRes_vb","");
        map.put("login_heading_vb","");
        map.put("forgot_secret_number_vb","");
        map.put("login_app_desc_1_vb","");
        map.put("login_app_desc_2_vb","");
        map.put("login_app_desc_3_vb","");
        map.put("login_app_desc_4_vb","");
        map.put("login_app_desc_5_vb","");
        map.put("label_submit_upload_ads_vb","");
        map.put("r_u_new_user_label_vb","");
        map.put("go_to_register_here_vb","");
        map.put("secretNum_input_label_vb","");
        map.put("reset_secret_heading_vb","");
        map.put("email_input_label_vb","");
        map.put("phone_input_label_vb","");
        map.put("use_phone_auth_vb","");
        map.put("use_email_auth_vb","");
        map.put("old_secretNum_input_label_vb","");
        map.put("required_label_vb","");
        map.put("required_email_phone_label_vb","");
        map.put("reset_secret_message_vb","");
        map.put("label_close_vb","");
        map.put("loginMsg_vb","");
        map.put("subject_vb","");
        map.put("loadAds_subject_vb","");        
        map.put("search_vb","");        
        map.put("ownerPhone_vb","");
        map.put("ownerEmail_vb","");
        map.put("secretNumber_vb","");
        map.put("userName_vb","");
        map.put("userId_vb","");
        map.put("search_vb","");
        map.put("likedItemRowId_vb","");
        map.put("message_vb","");
        map.put("status_vb","");
        map.put("registerForm_vb","");
        map.put("recordPlainTrack_vb","");        
        map.put("saveLikedItemIdsUri_vb","");        
        map.put("loadLikedItemIdsUri_vb","");    
        map.put("recordTrackUri_vb","");        
        map.put("resetSecretNum_vb","");       
        map.put("getAllCategoryUri_vb","");        
        map.put("logoutUri_vb","");        
        map.put("userInfoUri_vb","");   
        map.put("authorizeMsg_vb",""); 
        map.put("login_vb","");
        map.put("categoryName_vb","");
        map.put("id_vb",""); 
        map.put("toggleEmailActive_vb",""); 
        map.put("msgSeek_vb","");  
        map.put("httpCodes_vb",""); 
        map.put("adType_vb","");
        map.put("login_required_msg_vb","");
        map.put("logInOutEventsubscription_vb",""); 
        map.put("logInOut_subject_vb",""); 
        map.put("loginId_vb","");        
        map.put("loginName_vb","");        
        map.put("old_secretNumber_vb","");
        map.put("uploadUrl_vb","");
        map.put("webViewerProperties_vb","");      
        map.put("p1_vb","");            
        map.put("selectedFilter_vb","");              
        map.put("selectedAdType_vb","");              
        map.put("old_secretNum_input_label_vb","");               
        map.put("changeLangEventsubscription_vb","");              
        map.put("changeLang_subject_vb","");              
        map.put("ViewerScreenMsg_vb","");      
        map.put("doneFlag_vb","");                      
        map.put("doneMsg_vb","");              
        map.put("lang_change_not_done_vb","");      
        map.put("lang_change_done_vb","");              
        map.put("loginScreen_vb","");              
        map.put("userSettingsMsg_vb","");             
        map.put("adDisplayType_vb","");              
        map.put("uploadedFileName_vb","");      
        map.put("contentDesc_vb","");              
        map.put("createdOn_vb","");              
        map.put("activeDate_vb","");              
        map.put("showLoginRequiredMsg_vb","");             
        map.put("myAd_vb","");             
        map.put("userInfo_vb","");     
        map.put("user_settings_screen_vb","");             
        map.put("change_lang_menu_vb","");             
        map.put("logoutFlag_vb","");             
        map.put("changeLangUri_vb","");    
        map.put("loadLangPropertiesMsgUri_vb","");    
        map.put("webViewerProperties_vb",""); 
        map.put("cookieService_vb",""); 
        map.put("err_vb",""); 
        
        
        
        map.put("cartDeliveryAddressMsg_vb","");
        map.put("confirm_address_heading_msg_vb","");
        map.put("address_heading_msg_vb","");
        map.put("deliver_to_address_btn_msg_vb","");  
        map.put("new_address_msg_vb","");  
        map.put("deliver_to_new_address_btn_msg_vb","");
        map.put("delivery_address_heading_msg_vb","");
        map.put("confirm_address_btn_msg_vb","");
        map.put("thank_heading_vb","");
        map.put("thank_instruction_1_vb","");
        map.put("thank_instruction_2_vb","");
        map.put("thank_instruction_3_vb","");
        map.put("my_orders_heading_vb",""); 
        map.put("qnty_msg_vb",""); 
        map.put("status_msg_vb",""); 
        map.put("my_orders_msg_vb",""); 
        map.put("language_vb",""); 
//        map.put("",""); 
//        map.put("",""); 
//        map.put("",""); 
//        map.put("",""); 
//        map.put("",""); 
        map.put("error_vb",""); 
        map.put("cartToolbarMsg_vb",""); 
        map.put("placeholderText_vb",""); 
        map.put("label_submit_upload_ads_vb",""); 
        map.put("login_vb",""); 
        map.put("logout_vb",""); 
        map.put("main_menu_msg_vb",""); 
        map.put("merchant_upload_screen_msg_vb",""); 
        map.put("merchant_sell_product_msg_vb",""); 
        map.put("userLoginYes_vb","");         
        map.put("userLoginDto_vb","");         
        map.put("success_vb","");         
        map.put("processingAddToCart_vb","");         
        map.put("refreshCart_vb","");                 
        map.put("cart_seq_vb","");   
        map.put("cartStatus_vb","");
        map.put("plusOrMinus_vb","");
        map.put("responseSuccess_vb","");        
        map.put("cartScreenMsg_vb","");
        map.put("placeOrder_msg_vb","");
        map.put("orderPlaced_msg_vb","");
        map.put("orderConfirm_msg_vb","");
        map.put("orderRemove_msg_vb","");
        map.put("dontDelete_msg_vb","");
        map.put("confirmRemove_msg_vb","");
        map.put("ru_sureDelete_msg_vb","");
        map.put("currency_msg_vb","");
        map.put("cart_heading_msg_vb","");
        map.put("cart_empty_msg_vb","");
        map.put("qntty_msg_vb","");
        map.put("pay_msg_vb","");
        map.put("cart_cost_tax_msg_vb","");
        map.put("total_cost_msg_vb","");
        map.put("confirm_order_msg_vb","");
        map.put("refresh_cost_msg_vb","");
        map.put("imp_instructions_msg_vb","");
        map.put("instructions_1_msg_vb","");
        map.put("instructions_2_msg_vb","");
        map.put("instructions_3_msg_vb","");
        map.put("newAddressForm_vb","");
        map.put("newAddressFormCl_vb","");
        map.put("confirmAddress_vb","");
        map.put("addressClick_vb","");
        map.put("deliveryAddresses_vb","");
        map.put("addressCnt","");
        map.put("addressCurrentLength_vb","");
        map.put("newAddress_vb","");
        map.put("currentLength_vb","");   
        map.put("maxLength_vb","");
        map.put("clickSearchEventsubscription_vb","");    
        map.put("clickLikedAdsEventsubscription_vb","");
        map.put("logInOutEventsubscription_vb","");
        map.put("listProdFromCartUri_vb","");
        map.put("addProdToCartUri_vb","");
        map.put("productOrderPlacedUri_vb","");
        map.put("showAllOrderPlacedUri_vb","");
        map.put("eTarget_vb","");
        map.put("event_vb","");
        map.put("loadLikedAds_subject_vb","");     
        map.put("order_seq_vb","");  
        map.put("showLikedAds_vb","");  
        map.put("emptyCart_vb","");  
        map.put("getCartProdUri_vb","");  
        return map;
    }
    
    
   public LinkedHashMap<String,String>  cssVariables(){ 
        
        LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 
        map.put("toolbar","");
        map.put("container1","");
        map.put("register-form","");
        map.put("register-form-adj","");
        map.put("error_msg","");
        map.put("cancelbtn","");
        map.put("imgcontainer","");
        map.put("container","");
        map.put("register-form","");
        map.put("login-form","");
        map.put("login-form-adj","");
        map.put("error_msg","");
        map.put("imgcontainer","");
        map.put("container","");
        return map;
    }
   
   LinkedHashMap<String,String>  languageHiding(){
        
            LinkedHashMap<String,String> map = new LinkedHashMap<String,String>(); 
    
            map.put("bng","");
            map.put("en","");
            map.put("gj","");
            map.put("hn","");
            map.put("kn","");
            map.put("ur","");
            map.put("ml","");
            map.put("mr","");
            map.put("pa","");
            map.put("ta","");
            map.put("te","");
            
            return map;
    }
}