/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  sunjiv6
 * Created: 26 June, 2020
 */
create table category_model (id bigint not null auto_increment, category_name_bn varchar(80), category_name_en varchar(80), category_name_gu varchar(80), category_name_hi varchar(80), category_name_kn varchar(80), category_name_ml varchar(80), category_name_mr varchar(80), category_name_pa varchar(80), category_name_ta varchar(80), category_name_te varchar(80), category_name_ur varchar(80), created_on varchar(20), status varchar(1), primary key (id));
create table owner_target_area (id bigint not null auto_increment, all_targets varchar(1000), target varchar(20), user_owner_id bigint, primary key (id));


create table owner_content (id bigint generated by default as identity, active_date varchar(255), ad_display_type integer, ad_type integer, content_desc varchar(1000), created_on varchar(20), directory_paths_id integer, generated_file_name varchar(30), owner_user_id bigint, status varchar(1), uploaded_file_name varchar(50), primary key (id));
create table owner_target_area (id bigint generated by default as identity, all_targets Clob, target Clob, user_owner_id bigint, primary key (id));
create table security_api (id bigint generated by default as identity, apikey varchar(50), created_on varchar(50), owner_user_id bigint, status varchar(1), updated_on varchar(50), uri_accessed varchar(1000), viewer_user_id bigint, primary key (id));
create table transaction_money (id bigint generated by default as identity, transaction_date varchar(20), transaction_owner_id bigint, transaction_string varchar(80), updated_by_user bigint, primary key (id));
create table user_ad_viewer (id bigint generated by default as identity, ad_viewer_email varchar(50), ad_viewer_phone varchar(15), create_count integer, create_limit integer, secret_number varchar(4), transaction_id bigint, user_created_date varchar(20), user_name varchar(10), user_status varchar(1), user_type varchar(1), primary key (id));
create table user_ad_viewer_liked_it (id bigint generated by default as identity, all_liked_ids varchar(1000), user_ad_viewer_id bigint, primary key (id));
create table user_owner (id bigint generated by default as identity, create_count integer, create_limit integer, secret_number_encoded varchar(4), user_created_date varchar(20), user_email varchar(50), user_name varchar(50), user_phone varchar(15), user_type integer, primary key (id));



